/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{

	//1. Configure clock source for MCO1
#define RCC_CONFIG_OFFSET 0X08UL
#define RCC_BASE_ADDR 0x40023800UL
#define RCC_CONFIG_ADDR (RCC_BASE_ADDR + RCC_CONFIG_OFFSET)

	uint32_t *rcc_config_addr = (uint32_t *)RCC_CONFIG_ADDR;

	*rcc_config_addr &= ~(0x3 <<21); //HSI SELECTED

	//2. ENABLE GPIO PERIPHERAL CLOCK

	#define RCC_AHB1ENR_OFFSET 0X30UL
	#define RCC_BASE_ADDR 0x40023800UL
	#define RCC_AHB1ENR_ADDR (RCC_BASE_ADDR + RCC_AHB1ENR_OFFSET)

		uint32_t *rcc_ahb1enr_addr = (uint32_t *) RCC_AHB1ENR_ADDR;

		*rcc_ahb1enr_addr  |= (0x1 <<0); //Bit 0 enabled

		//3. CHANGE PA8 TO AF0 MODE

#define GPIOA_MODER_OFFSET 0x00UL
#define GPIOA_BASE_ADDR 0x40020000UL
#define GPIOA_MODER_ADDR  (GPIOA_BASE_ADDR + GPIOA_MODER_OFFSET)

		uint32_t * gpioa_moder_addr = (uint32_t *)GPIOA_MODER_ADDR;

		*gpioa_moder_addr |= (0x1<<17);  //SET
		*gpioa_moder_addr &= ~(0x1<<16); //CLEAR

		//4. af0 mode
#define GPIOA_AFHR_OFFSET  0x24UL
#define GPIOA_AFHR_ADDR  (GPIOA_BASE_ADDR + GPIOA_AFHR_OFFSET)

		uint32_t * gpioa_afhr_addr = (uint32_t *)GPIOA_AFHR_ADDR;

		*gpioa_afhr_addr &= ~(0xF<<0); //CLEAR
////////////////////////////////////////////////////
		//GPIOA PA8 PORT CONFIGURED IN AF0 MODE AND CARRIES THE MCO1 SIGNAL CAN BE ANALYSED USING LOGIC ANALYSER

    /* Loop forever */
	for(;;);
}
